name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15]

    steps:

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'

    - name: "Install ceedling"
      run: sudo gem install ceedling
    - name: "Add Ceedling to PATH"
      run: export PATH="$PATH:~/.gem/ruby/2.5.0/bin"

    - name: "Install norminette"
      run: |
        git clone https://github.com/42Paris/norminette.git ~/.norminette/
        cd ~/.norminette/
        bundle

  build:
    needs: prepare

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15]

    steps:

    - name: "Clone actual repo"
      uses: actions/checkout@v2

    - name: "Show some info"
      run: |
        [[ command -v apt ]] && { pwd; sudo apt install tree; tree; cd ~/runner/libft/libft; pwd; tree; }

    - name: "Compile libft library"
      run: make

  test:
    needs: build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15]

    steps:
    - name: "cd into project root"
      run: cd ~/work/libft/libft

    - name: "Run unit-tests"
      run: ceedling

    - name: "Run norminette tests"
      run: make norm
