name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15]
    defaults:
        run:
          shell: bash

    steps:

    - name: "Setup Ruby for Ceedling and Norminette"
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'

    - name: "Clone actual repo"
      uses: actions/checkout@v2

    - name: "Compile libft library"
      run: make

    - name: "Install norminette"
      run: |
        git clone https://github.com/42Paris/norminette.git ~/.norminette/
        cd ~/.norminette/
        bundle

    - name: "Run norminette tests"
      run: make norm

    - name: "Install ceedling"
      run: sudo gem install ceedling
    - name: "Add Ceedling to PATH"
      run: export PATH="$PATH:~/.gem/ruby/2.5.0/bin:/usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.30.0/bin"

    - name: "Run unit-tests"
      run: ceedling