name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

      # Library compilation:
    - name: "Compile libft library"
      run: make

      # Unit-testing:
    - name: "Install ceedling"
      run: sudo gem install ceedling
    - name: "Add Ceedling to PATH"
      run: export PATH="$PATH:~/.gem/ruby/2.5.0/bin"
    - name: "Run unit-tests"
      run: ceedling

      # Norminetting (doesn't fail on errors!):
    - name: "Install norminette"
      run: |
        sudo apt-get install ruby ruby-bundler ruby-dev build-essential
        git clone https://github.com/42Paris/norminette.git ~/.norminette/
        cd ~/.norminette/
        bundle
    - name: "Run norminette tests"
      run: |
        make norm
