name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    # - name: "Copy gnl header to the tests dir"
    #   run: ln -s includes/get_next_line.h test/includes/get_next_line.h
    - name: "Install ceedling"
      run: sudo gem install ceedling
    - name: "Add Ceedling to PATH"
      run: export PATH="$PATH:~/.gem/ruby/2.5.0/bin"
    - name: "Compile libft library"
      run: make
    - name: "Run unit tests"
      run: ceedling
